version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - ./server:/app
    ports:
      - '8880:8880'
    command: npm run dev

  client:
    depends_on:
      - server
    env_file: ./client/.env
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: "./client"
    volumes:
      - ./client:/app
    ports:
      - '3000:3000'
    command: npm run start
